[package]
authors = ["Scott Olson <scott@solson.me>"]
description = "An experimental interpreter for Rust MIR."
license = "ISC"
name = "miri"
repository = "https://github.com/tsion/miri"
version = "0.1.0"

[[bin]]
doc = false
name = "miri"

[dependencies]
byteorder = "0.4.2"
log = { path = "../log" }
env_logger = { path = "../log/env" }
